version: '3.9'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - rabbit
    ports:
      - "8000:8000"
  consumer:
    build: .
    command: python manage.py consume_sms
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - rabbit
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sms_relay
    ports:
      - "5432:5432"
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
