version: '3.8'

services:
  server-a:
    build:
      context: ./server-a
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "${SERVER_A_PORT:-8000}:${SERVER_A_PORT:-8000}"
    depends_on:
      - redis
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_A_PORT:-8000}/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  server-b:
    image: alpine/git
    command: ["sh", "-c", "echo 'Server B placeholder' && sleep infinity"]
    volumes:
      - ./server-b:/app

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./.env
    ports:
      - "${FRONTEND_PORT:-5173}:80"
    depends_on:
      - server-b
