# Generated by Django 5.2.5 on 2025-08-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('send_url', models.URLField()),
                ('balance_url', models.URLField()),
                ('default_sender', models.CharField(blank=True, help_text='Optional default sender (line number) for this provider.', max_length=32)),
                ('auth_type', models.CharField(choices=[('none', 'No Auth'), ('basic', 'Basic Auth'), ('api_key_header', 'API Key in Header'), ('api_key_query', 'API Key in Query Param'), ('oauth2_client', 'OAuth2 Client Credentials')], default='basic', max_length=20)),
                ('auth_config', models.JSONField(blank=True, default=dict, help_text='Provider-specific auth data. Examples:\n- BASIC: {"username": "u", "password_env": "MAGFA_PASSWORD", "domain": "d"}\n- API_KEY_HEADER: {"key": "...", "header_name": "Authorization"}\n- API_KEY_QUERY: {"key": "...", "param_name": "api_key"}\n- OAUTH2_CLIENT: {"token_url": "...", "client_id": "...", "client_secret_env": "...", "scope": "..."}')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Static headers to send with every request.')),
                ('query_params', models.JSONField(blank=True, default=dict, help_text='Static query params to append to every request.')),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.AddIndex(
            model_name='smsprovider',
            index=models.Index(fields=['is_active', 'slug'], name='providers_s_is_acti_cabfc3_idx'),
        ),
    ]
