# Generated by Django 5.2.5 on 2025-08-25 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_smsprovider_delete_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsprovider',
            name='priority',
            field=models.PositiveSmallIntegerField(default=50, help_text='Provider priority, from 0 (lowest) to 100 (highest).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='smsprovider',
            name='auth_config',
            field=models.JSONField(blank=True, default=dict, help_text='Provider-specific auth data. Examples:\n- BASIC: {"username": "u", "password_env": "MAGFA_PASSWORD", "domain": "d"}- API_KEY_HEADER: {"key": "...", "header_name": "Authorization"}- API_KEY_QUERY: {"key": "...", "param_name": "api_key"}- OAUTH2_CLIENT: {"token_url": "...", "client_id": "...", "client_secret_env": "...", "scope": "..."}'),
        ),
    ]
