# Generated by Django 5.2.5 on 2025-08-25 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_smsprovider_priority_alter_smsprovider_auth_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsprovider',
            options={'ordering': ['-priority', 'name']},
        ),
        migrations.AddField(
            model_name='smsprovider',
            name='provider_type',
            field=models.CharField(choices=[('magfa', 'Magfa')], default='magfa', max_length=16),
        ),
        migrations.AlterField(
            model_name='smsprovider',
            name='auth_config',
            field=models.JSONField(blank=True, default=dict, help_text='Provider-specific auth data. Examples:\n- BASIC: {"username": "u", "password_env": "MAGFA_PASSWORD", "domain": "d"}\n- API_KEY_HEADER: {"key": "...", "header_name": "Authorization"}\n- API_KEY_QUERY: {"key": "...", "param_name": "api_key"}\n- OAUTH2_CLIENT: {"token_url": "...", "client_id": "...", "client_secret_env": "...", "scope": "..."}'),
        ),
        migrations.AlterField(
            model_name='smsprovider',
            name='default_sender',
            field=models.CharField(help_text='Line number (sender) represented by this provider instance.', max_length=32),
        ),
        migrations.AlterField(
            model_name='smsprovider',
            name='priority',
            field=models.PositiveSmallIntegerField(default=50, help_text='Higher means higher priority (unique per provider_type).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='smsprovider',
            index=models.Index(fields=['provider_type', 'is_active', 'priority'], name='providers_s_provide_ffb7dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='smsprovider',
            constraint=models.UniqueConstraint(fields=('provider_type', 'default_sender'), name='uq_provider_type_sender'),
        ),
        migrations.AddConstraint(
            model_name='smsprovider',
            constraint=models.UniqueConstraint(fields=('provider_type', 'priority'), name='uq_priority_per_provider_type'),
        ),
    ]
