# Generated by Django 5.2.5 on 2025-08-23 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("type", models.CharField(max_length=50)),
                ("base_url", models.URLField()),
                ("endpoint_send", models.CharField(max_length=200)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("apikey", "API Key"),
                            ("bearer", "Bearer"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("basic_username", models.CharField(blank=True, max_length=200)),
                ("basic_password", models.CharField(blank=True, max_length=200)),
                ("default_sender", models.CharField(blank=True, max_length=20)),
                ("extra_headers", models.JSONField(blank=True, null=True)),
                ("timeout_ms", models.IntegerField(default=5000)),
                ("retries", models.IntegerField(default=3)),
                ("retry_backoff_ms", models.IntegerField(default=1000)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
