# Generated by Django 5.2.5 on 2025-08-27 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0004_alter_smsprovider_options_smsprovider_provider_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.UUIDField(db_index=True, help_text='The unique tracking ID from Server A for end-to-end tracing', unique=True)),
                ('recipient', models.CharField(help_text='The phone number of the recipient', max_length=20)),
                ('text', models.TextField(help_text='The content of the SMS')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent to Provider'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected internally')], db_index=True, default='PENDING', max_length=20)),
                ('send_attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of failed attempts to send')),
                ('provider_message_id', models.CharField(blank=True, db_index=True, help_text="Message ID from the provider's system (for webhooks)", max_length=255, null=True)),
                ('provider_response', models.JSONField(blank=True, help_text='The full API response from the provider', null=True)),
                ('error_message', models.TextField(blank=True, help_text='The last error message if the sending failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was received from the queue')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last status update')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Timestamp of successful sending to the provider', null=True)),
                ('provider', models.ForeignKey(blank=True, help_text='The provider used for sending this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='providers.smsprovider')),
                ('user', models.ForeignKey(help_text='The user who initiated the SMS request', on_delete=django.db.models.deletion.PROTECT, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='messaging_m_status_17edaf_idx')],
            },
        ),
    ]
