# Generated by Django 5.2.5 on 2025-08-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("AWAITING_RETRY", "Awaiting Retry"),
                    ("SENT", "Sent to Provider"),
                    ("DELIVERED", "Delivered"),
                    ("FAILED", "Failed"),
                    ("REJECTED", "Rejected internally"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
