# Generated by Django 5.2.5 on 2025-08-31 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_alter_message_status"),
        (
            "providers",
            "0004_alter_smsprovider_options_smsprovider_provider_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageAttemptLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILURE", "Failure")],
                        max_length=10,
                    ),
                ),
                ("provider_response", models.JSONField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempt_logs",
                        to="messaging.message",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="The provider used for this attempt",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempt_logs",
                        to="providers.smsprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
