# Generated by Django 5.2.5 on 2025-08-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_messageattemptlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="initial_envelope",
            field=models.JSONField(
                blank=True,
                help_text="The full envelope received from the queue",
                null=True,
            ),
        ),
    ]
