# Generated by Django 5.2.5 on 2025-09-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0004_message_initial_envelope"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the provider confirmed final delivery",
                null=True,
            ),
        ),
    ]
