# Generated by Django 5.2.5 on 2025-09-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0005_message_delivered_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="The cost of the message as reported by the provider.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
