# Generated by Django 5.2.5 on 2025-08-25 06:10

from django.db import migrations


def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('user_management', 'Profile')
    db_alias = schema_editor.connection.alias

    for user in User.objects.using(db_alias).all():
        if not hasattr(user, 'profile'):
            Profile.objects.using(db_alias).create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_profiles_for_existing_users, migrations.RunPython.noop),
    ]