# Generated by Django 5.2.5 on 2025-08-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20250825_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_quota',
            field=models.IntegerField(default=0),
        ),
    ]
