# Generated by Django 5.2.5 on 2025-08-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_profile_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
