# Generated by Django 5.2.5 on 2025-08-23 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tracking_id", models.CharField(max_length=64, unique=True)),
                ("customer_id", models.CharField(max_length=64)),
                ("provider_message_id", models.JSONField(blank=True, null=True)),
                ("policy_snapshot", models.JSONField(blank=True, null=True)),
                ("payload_hash", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "unique_together": {("idempotency_key", "provider")},
            },
        ),
        migrations.CreateModel(
            name="MessageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("raw", models.JSONField(blank=True, null=True)),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="messaging.message",
                    ),
                ),
            ],
        ),
    ]
